### ISSUE TITLE
Attribute error introduced between 0.3.2 and 0.4.0

### ISSUE THREAD

**Issue by Erotemic** [Kitware/nrtk-explorer#136]
On my local nrtk-explorer checkout, if I grab the latest code and run: 

```
COCO_DSET=$(kwcoco toydata vidshapes8 | tail -n1)
nrtk-explorer --dataset $COCO_DSET
```

I get an error:

```
q-card.state is missing
Traceback (most recent call last):
  File "/home/joncrall/.pyenv/versions/3.11.9/envs/pyenv3.11.9/bin/nrtk-explorer", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/main.py", line 5, in main
    engine = Engine(server)
             ^^^^^^^^^^^^^^
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/core.py", line 96, in __init__
    self._build_ui()
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/core.py", line 155, in _build_ui
    self.ui = ui.NrtkExplorerLayout(
              ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/ui/layout.py", line 171, in __init__
    NrtkDrawer(
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/ui/layout.py", line 23, in __init__
    with ui.CollapsibleCard() as card:
         ^^^^^^^^^^^^^^^^^^^^
  File "/home/joncrall/code/nrtk-explorer/src/nrtk_explorer/app/ui/collapsible_card.py", line 14, in __init__
    self.state.client_only(name)  # keep it local if not provided
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'client_only'
```

Whereas if I checkout tag `v0.3.2`, it works fine.

I did some bisecting and I found that the error was introduced in `5fafd291376d3c284fab9400e91368e91a03544a` @jourdain

**Comment by jourdain** [comment]
Can you try doing a `pip install trame-client -U`
It might be the case, I was not explicit enough in version requirement on the trame side.

**Comment by Erotemic** [comment]
That works. I had `trame-client-3.0.3`, and updating to `trame-client-3.3.2` removes the issue.

**Comment by Erotemic** [comment]
I tend to be in favor of including important transitive dependencies in requirements that are explicitly used (although I'm not sure if it is explicitly used here).

**Comment by jourdain** [comment]
We are indeed assuming available API that only exist on those version of trame-client. I think for now, you should add that `trame-client>=3.3` in our pyproject.

Down the road when trame enforce newer version for client/server we could put the constraint on trame itself.
